config/routes.rb
Flamingle::Application.routes.draw do

  match "dashboard" => "dashboard#show"
 
  resources :missions
 
  match 'missions/:id/accept' => 'mission_attempts#create', :as => :accept_mission
  match 'missions/:id/abandon' => 'mission_attempts#destroy', :as => :abandon_mission
  match 'missions/:id/complete' => 'mission_attempts#update', :as => :complete_mission
  match 'missions/:id/approve/:user_id' => 'missions#approve', :as => :approve_mission

  root :to => "home#index"

  devise_for :users, 
    :path_names => { :sign_up => "register", :sign_in => "login" }

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @attempted_missions = current_user.attempted_missions
    @created_missions = current_user.missions
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>
<p>Hello, <em><%= current_user.username %></em>. How's the weather up there?</p>
<h2>Missions You're Attempting</h2>
<div class='missionslist'>
<ul>
<% @attempted_missions.each do |mission| %>
  <li>
  	<a href='missions/<%= mission.id %>'>
  	
	
    <span class='title'><%= mission.title %></span>
    <span class='description'><%= mission.short_description %></span>
    <% # mission.user.try(:username), mission.priority %>
 	
 	<% if mission.mission_attempts.find_by_user_id(current_user.id).status == 'Done' %>
 		<div class='done_waiting_approval'></div>
	<% else %>
 		<%= link_to '', complete_mission_url(mission), :confirm => 'Are you sure you have completed this mission to it\'s specifications?', :class=>'done' %>
  	<% end %>
  	</a>
  </li>
<% end %>
</ul>
</div>

<h2 class='owner'>Missions You've Created</h2>
<div class='missionslist'>
<ul>
<% @created_missions.each do |mission| %>
	<li>
		<a href='missions/<%= mission.id %>'>
    	<span class='title'><%= mission.title %></span>
    	<span class='description'><%= mission.short_description %></span>
    
        <!-- 
        <% if can?(:update, mission) %>
        	<%= link_to 'Edit', edit_mission_path(mission) %>
        <% end %>
        <% if can?(:destroy, mission) %>
        	<%= link_to 'Delete', mission, :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
        -->
       </a> 
  </li>
<% end %>
</ul>
</div>

<h2 class='past'>Past Missions</h2>
<div class='missionslist'>
<ul>


</ul>
</div>