config/routes.rb
Flamingle::Application.routes.draw do

  match "dashboard" => "dashboard#show"
 
  resources :missions
 
  match 'missions/:id/accept' => 'mission_attempts#create', :as => :accept_mission
  match 'missions/:id/abandon' => 'mission_attempts#destroy', :as => :abandon_mission
  match 'missions/:id/complete' => 'mission_attempts#update', :as => :complete_mission
  match 'missions/:id/approve/:user_id' => 'missions#approve', :as => :approve_mission

  root :to => "home#index"

  devise_for :users, 
    :path_names => { :sign_up => "register", :sign_in => "login" }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_url
    else
      render :layout => false
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flamingle</title>
  <%= stylesheet_link_tag "splash.css" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,400,600,700,800' rel='stylesheet' type='text/css'>
  
</head>
<body>

<h1>Flamingle BETA</h1>
<a id='dashboard' href="/dashboard">Dashboard</a>
<a id='missions' href="/missions">Missions</a>

<h2>Sign in</h2>

<%= form_for("user", :url => user_session_path) do |f| %> 
   <%= f.label :login %> <br/> 
   <%= f.text_field :login , :size=>'15',:maxlength=>'32' %> <br/> 
   <%= f.label :password %> <br/> 
   <%= f.password_field :password , :size=>'15', :maxlength=>'32' %> 
<br/> 
   <%= f.submit "Sign in" %> <br /> 
   <%= link_to "Forgot your password?", new_password_path('user')  %> 
 <% end %>
 
<h2>Register</h2>

<%= form_for("user", :url => user_registration_path,:method => :post) do |f| %> 
     <p><%= f.label :email %><br />
  <%= f.email_field :email %></p>

  <p><%= f.label :username %><br />
  <%= f.text_field :username %></p>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Sign up" %></p>
 <% end %>




</body>
</html>