config/routes.rb
Flamingle::Application.routes.draw do

  match "dashboard" => "dashboard#show"
 
  resources :missions
 
  match 'missions/:id/accept' => 'mission_attempts#create', :as => :accept_mission
  match 'missions/:id/abandon' => 'mission_attempts#destroy', :as => :abandon_mission
  match 'missions/:id/complete' => 'mission_attempts#update', :as => :complete_mission
  match 'missions/:id/approve/:user_id' => 'missions#approve', :as => :approve_mission

  root :to => "home#index"

  devise_for :users, 
    :path_names => { :sign_up => "register", :sign_in => "login" }

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :user
  belongs_to :mission_priority
 
  has_many :attempting_users, :through => :mission_attempts, :source => :user
  has_many :mission_attempts do
    
    def new(user)
      create(:user_id => user.id)
      find_by_user_id(user.id).set_status "In Progress"
    end

    def abandon(user)
      find_by_user_id(user.id).destroy
    end
    
    def approve(user_id)
      update_all(:status => "Inactive")#:mission_attempt_status_id => MissionAttemptStatus.find_by_name("Inactive"))
      find_by_user_id(user_id).set_status "Approved"
    end

  end

  after_initialize :init

  def init
    # set default values if nil
    self.active ||= true
  end

  def priority
    self.mission_priority.try(:name)
  end
  
  def status
    if self.mission_attempts.size > 0
      if self.mission_attempts.find_by_status("Done")
        "Pending Approval"
      elsif self.mission_attempts.find_by_status("Approved")
        "Completed"
      else
        "In Progress"
      end
    else
      "Available"
    end 
  end

  def short_description
    if self.description
      if self.description.size > 100
  	    self.description[0 .. 100] + '...'
  	  else 
  	    self.description
  	  end
    end
  end
  
  def human_time
    self.created_at.strftime("%b %d, %Y at %I:%M%p")
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource

  # GET /missions
  # GET /missions.xml
  def index
    @missions = Mission.all(:include => :user)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @missions }
    end
  end

  # GET /missions/1
  # GET /missions/1.xml
  def show
    # @mission = Mission.find(params[:id], :include => :user)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mission }
    end
  end

  # GET /missions/new
  # GET /missions/new.xml
  def new
    # @mission = Mission.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mission }
    end
  end

  # GET /missions/1/edit
  def edit
    # @mission = Mission.find(params[:id])
  end

  # POST /missions
  # POST /missions.xml
  def create
    @mission = current_user.missions.create(params[:mission])

    respond_to do |format|
      if @mission.save
        flash[:notice] = "You created a mission! Well done."
        format.html { redirect_to @mission }
        format.xml  { render :xml => @mission, :status => :created, :location => @mission }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /missions/1
  # PUT /missions/1.xml
  def update
    # @mission = Mission.find(params[:id])

    respond_to do |format|
      if @mission.update_attributes(params[:mission])
        flash[:notice] = "Your mission details were updated successfully."
        format.html { redirect_to @mission }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.xml
  def destroy
    # @mission = Mission.find(params[:id])
    @mission.destroy

    respond_to do |format|
      format.html { redirect_to(missions_url) }
      format.xml  { head :ok }
    end
  end
  
  # PUT /missions/1/approve/2
  def approve
    authorize! :manage, @mission
    
    @mission.mission_attempts.approve(params[:user_id])
    @mission.save

    flash[:notice] = "Your mission is complete! " + User.find(params[:user_id]).username + " will be rewarded for finishing the task."
    redirect_to dashboard_url
    return
  end

end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= form_for(@mission) do |f| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission.errors.count, "error") %> prevented this mission from being saved:</h2>

      <ul>
      <% @mission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= collection_select :mission, :mission_priority_id, MissionPriority.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render 'form' %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<h1>Missions Control Panel</h1>
<h2>Listing All Missions</h2>
<div class='missionslist'>
<ul>
<% @missions.each do |mission| %>
	<li>
		<a href='missions/<%= mission.id %>'>
    	<% if mission.user == current_user %>
    		<div class='mission_badge mission_owner'></div>
    	<% end %>
    	<% if mission.mission_priority.name == 'High' %>
    		<div class='mission_badge mission_high'></div>
    	<% end %>
    	<span class='title'><%= mission.title %></span>
    	<span class='description'><%= mission.short_description %></span>
        <!-- 
        <% if can?(:update, mission) %>
        	<%= link_to 'Edit', edit_mission_path(mission) %>
        <% end %>
        <% if can?(:destroy, mission) %>
        	<%= link_to 'Delete', mission, :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
        -->
       </a> 
  </li>
<% end %>
</ul>
</div>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render 'form' %>

<%= link_to 'Back', missions_path %>

app/views/missions/show.html.erb
<h1>MISSION: <em><%= @mission.title %></em></h1>
<p>
<%= @mission.description %>
</p>
<h2 class='owner'>Status: <span class='<%= @mission.status.downcase %>'><%= @mission.status %></span></h2>
<p>
Posted by: <span class='user'><%= @mission.user.try(:username) %></span><br />
Posted on: <span class='heavy'><%= @mission.human_time %></span><br />
</p>

<% if @mission.status != "Complete" %>
  <%= link_to_if (can? :accept, @mission), 'Accept', accept_mission_path(@mission) %> |
  <% if can? :manage, @mission %>
    <%= link_to 'Edit', edit_mission_path(@mission) %> |
    <%= link_to 'Delete', mission_path(@mission), 
                :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>
  <%= link_to 'Back', missions_path %>
<% end %>

<h2>Mission Attempts</h2>
<ul id="mission_attempts">
<% @mission.mission_attempts.each do |attempt| %>
  <li>
    <span class='user'><%= attempt.user.username %></span> is <%= attempt.status.downcase %>
    <% if attempt.status == "Done" %>
    	- waiting for <%= @mission.user.try(:username) %>'s approval
    <% end %>
    <% if @mission.user == current_user %>
    <div class='mission_approve'>
      <%= link_to "Approve", approve_mission_path(@mission, attempt.user.id) if attempt.status == "Done" %>
    </div>
    <% end %>
  </li>
<% end %>
</ul>