config/routes.rb
Flamingle::Application.routes.draw do

  match "dashboard" => "dashboard#show"
 
  resources :missions
 
  match 'missions/:id/accept' => 'mission_attempts#create', :as => :accept_mission
  match 'missions/:id/abandon' => 'mission_attempts#destroy', :as => :abandon_mission
  match 'missions/:id/complete' => 'mission_attempts#update', :as => :complete_mission
  match 'missions/:id/approve/:user_id' => 'missions#approve', :as => :approve_mission

  root :to => "home#index"

  devise_for :users, 
    :path_names => { :sign_up => "register", :sign_in => "login" }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flamingle</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,400,600,700,800' rel='stylesheet' type='text/css'>
  
</head>
<body>

<div id='header'>
	<div id='container'>
		<div id='logo'><a href='/'></a></div>
		<div id='menu'>
			<ul>
				<li><a id='dashboard' href="/dashboard"></a></li>
				<li><a id='missions' href="/missions"></a></li>
				<li id='menu_end'></li>
			</ul>
		</div>
	</div>
</div>

<% flash.each do |name, msg| %>
<div class='message'>
  <%= content_tag(:span, msg, :id => "flash_#{name}") %>
</div>
<% end %>

<div id='content_top'></div>
<div id='content'>
	<div id='container'>
		<div id='leftbar'>
			
			


		
			<div id="auth">
			  <% if user_signed_in? %>
			    <div id='create_mission'><%= link_to '', new_mission_path %></div>
			    
				<p>
				<center><img src='/images/sidebar_minime.png'/></center><br />
				Planet: <span class='heavy'>Heroku</span><br />
				Nickels: <span class='heavy'>410</span>
				</p>
				
			    <%= current_user.username %>
			    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
			    
			  <% else %>
			  
			    <div id='anon'></div>
			    <div id='login'><%= link_to "", new_user_session_path %></div>
			    <div id='register'><%= link_to "", new_user_registration_path %></div>
			   
			  <% end %>
			</div>
			
			
		</div>
		<div id='rightbar'>
		
			<%= yield %>
			
		</div>
	</div>
</div>
<div id='content_bottom'></div>


</body>
</html>